# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 991c596933b76de28213acb40c33188d8cc58c4a331a553e911db51fa718cad39597febffff2c26e3f3c5c3a45f423668c92833dda58a16e8dbfcf8404e05590

test:
  secret_key_base: 6d7e8e3c78fc35c25bba70e50e639a0602ed710fb5ee2b1e981d33537bc097e67cdaa58a140ee17dd7259ec6ba05de160787cf301643a0080b6d6ab1d404bb45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
